M48
; DRILL file KiCad 10.0.1 date 2026-05-19T21:18:31
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-19T21:18:31+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X13.97Y2.54
X15.24Y50.8
X66.04Y35.56
X66.04Y7.62
X90.17Y50.8
X96.52Y2.54
M30
