; PlatformIO Project Configuration File
;
;   PENS Expansion Board V2.0 - Full Hardware Test
;   Arduino Mega 2560
;
;   Build:    pio run
;   Upload:   pio run --target upload
;   Monitor:  pio device monitor

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
